name: with_pretrained
train_cfg:
  random_seed: 2022
  deterministic: True
  resume_checkpoint: null
  optimizer: Adam
  lr: 0.0001
  weight_decay: 0.001
  scheduler:
    milestones: [20, 40]
  epochs: 50

data_cfg:
  root_path: "/cluster/scratch/jingyli/iml/data"
  image_resize: [224, 224]
  loader_cfg:
    batch_size: 64
    num_workers: 4
    pin_memory: True

model_cfg:
  embedding_model:
    pretrain_model: "resnet"
    out_channels: 5
    feature_extract: False
  triplet_model:
    margin: 1


log_cfg:
  use_wandb_logger: True