train_cfg:
  random_seed: 2022
  deterministic: True
  resume_checkpoint: null
  optimizer: Adam
  lr: 0.0001
  weight_decay: 0.001
  scheduler:
    milestones: [100, 200]
  epochs: 100

data_cfg:
  root_path: "/cluster/scratch/jingyli/iml/data"
  image_resize: [240, 240]
  loader_cfg:
    batch_size: 128
    num_workers: 4
    pin_memory: True

model_cfg:
  embedding_model:
    out_channels: 2
  triplet_model:
    margin: 0.8

log_cfg:
  use_wandb_logger: True