name: train
pretrain_checkpoint: '/cluster/scratch/jingyli/iml/task4/train_logs/22-06-01_08-59-48_independent-hog-24'
train_model_cfg:
  model_type: "RandomForest"
output_root: "/cluster/scratch/jingyli/iml/task4/out"